import { mkdir, writeFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import ExcelJS from "exceljs";
import { buildCanonicalWorkbookBuffer } from "../src/lib/exportWorkbook";
import type { CanonicalDocument } from "../src/types/canonical";

const canonical: CanonicalDocument = { schemaVersion:"1.0", source:{fileName:"invoice.png",originalBytes:100,processedBytes:90,originalWidth:300,originalHeight:200,processedWidth:300,processedHeight:200,mimeType:"image/png"}, pages:[{pageNumber:1,width:300,height:200}], tables:[{id:"table-1",pageNumber:1,title:"Detected table",rows:2,columns:3,source:"ruled-grid",confidence:.9,cells:[{id:"a",tableId:"table-1",row:0,column:0,rowSpan:1,columnSpan:2,x:0,y:0,width:200,height:100,text:"Merged heading",sourceOcrIds:[],confidence:.9,warning:null,manuallyEdited:false},{id:"b",tableId:"table-1",row:0,column:2,rowSpan:1,columnSpan:1,x:200,y:0,width:100,height:100,text:"Amount",sourceOcrIds:[],confidence:.9,warning:null,manuallyEdited:false},{id:"c",tableId:"table-1",row:1,column:0,rowSpan:1,columnSpan:1,x:0,y:100,width:100,height:100,text:"Item",sourceOcrIds:[],confidence:.6,warning:"Low OCR confidence",manuallyEdited:false},{id:"d",tableId:"table-1",row:1,column:1,rowSpan:1,columnSpan:1,x:100,y:100,width:100,height:100,text:"",sourceOcrIds:[],confidence:null,warning:null,manuallyEdited:false},{id:"e",tableId:"table-1",row:1,column:2,rowSpan:1,columnSpan:1,x:200,y:100,width:100,height:100,text:"125.00",sourceOcrIds:[],confidence:.99,warning:null,manuallyEdited:false}]}],rawOcr:[],unassignedOcr:[],diagnostics:{tableCount:1}};

describe("browser XLSX export",()=>{ it("preserves sheets, merges, blanks, widths and diagnostics",async()=>{ const buffer=await buildCanonicalWorkbookBuffer(canonical); await mkdir("benchmarks/results",{recursive:true}); await writeFile("benchmarks/results/browser-export-compatibility.xlsx",new Uint8Array(buffer)); const workbook=new ExcelJS.Workbook(); await workbook.xlsx.load(buffer); expect(workbook.worksheets.map(sheet=>sheet.name)).toEqual(["Detected table","Raw OCR","Unassigned OCR","Diagnostics"]); const sheet=workbook.getWorksheet("Detected table"); expect(sheet?.getCell("A1").value).toBe("Merged heading"); expect(sheet?.getCell("B2").value).toBe(""); expect(sheet?.getCell("C2").value).toBe("125.00"); expect(sheet?.getColumn(1).width).toBe(18); expect(sheet?.model.merges??[]).toContain("A1:B1"); }); });
