import { describe, expect, it } from "vitest";
import { buildCanonicalDocument, transformPoint } from "../src/lib/fusion";
import type { BrowserGeometryResult, OcrBox } from "../src/types/canonical";

const identityGeometry = (rows: number, columns: number, size = 100): BrowserGeometryResult => ({ page_transform: { sourceWidth: columns * size, sourceHeight: rows * size, targetWidth: columns * size, targetHeight: rows * size, forward: [1,0,0,0,1,0,0,0,1], inverse: [1,0,0,0,1,0,0,0,1], perspectiveApplied: false, deskewDegrees: 0 }, table_candidates: [{ id: "table-1", x: 0, y: 0, width: columns * size, height: rows * size, confidence: .9 }], horizontal_lines: [], vertical_lines: [], row_boundaries: Array.from({length: rows + 1}, (_,i)=>i*size), column_boundaries: Array.from({length: columns + 1}, (_,i)=>i*size), cell_rectangles: Array.from({length: rows},(_,row)=>Array.from({length: columns},(_,column)=>({id:`table-1-r${row}-c${column}`,tableId:"table-1",row,column,rowSpan:1,columnSpan:1,x:column*size,y:row*size,width:size,height:size}))).flat(), diagnostics: {} });
const ocr = (id:string,text:string,left:number,top:number,right:number,bottom:number):OcrBox => ({ id, pageNumber:1, text, confidence:.98, box:[[left,top],[right,top],[right,bottom],[left,bottom]], readingOrder:Number(id.replace(/\D/g,""))||0, kind:"line" });
const build=(geometry:BrowserGeometryResult,items:OcrBox[])=>buildCanonicalDocument({fileName:"invoice.png",originalBytes:100,processedBytes:90,originalWidth:geometry.page_transform.sourceWidth,originalHeight:geometry.page_transform.sourceHeight,processedWidth:geometry.page_transform.targetWidth,processedHeight:geometry.page_transform.targetHeight,mimeType:"image/png",geometry,ocr:items,ocrDiagnostics:{}});

describe("OCR and geometry fusion",()=>{
  it("materializes blank cells without compacting later values",()=>{ const document=build(identityGeometry(2,3),[ocr("ocr-1","Medicine",5,5,80,25),ocr("ocr-2","Amount",205,5,280,25),ocr("ocr-3","100.00",205,105,280,125)]); expect(document.tables[0].cells).toHaveLength(6); expect(document.tables[0].cells.find(c=>c.row===1&&c.column===1)?.text).toBe(""); expect(document.tables[0].cells.find(c=>c.row===1&&c.column===2)?.text).toBe("100.00"); });
  it("keeps a line crossing several columns unresolved",()=>{ const document=build(identityGeometry(1,3),[ocr("ocr-1","unsafe wide line",70,20,230,55)]); expect(document.unassignedOcr.map(i=>i.text)).toContain("unsafe wide line"); expect(document.tables[0].cells.every(c=>c.text==="")).toBe(true); });
  it("reconstructs a borderless grid from shared OCR boxes",()=>{ const geometry=identityGeometry(0,0); Object.assign(geometry.page_transform,{sourceWidth:600,targetWidth:600,sourceHeight:300,targetHeight:300}); geometry.table_candidates=[];geometry.row_boundaries=[];geometry.column_boundaries=[];geometry.cell_rectangles=[]; const items:OcrBox[]=[]; for(let row=0;row<3;row++)for(let column=0;column<3;column++)items.push(ocr(`ocr-${row*3+column+1}`,`${row}:${column}`,column*180+20,row*80+20,column*180+80,row*80+40)); const document=build(geometry,items); expect(document.tables[0].source).toBe("borderless-ocr"); expect(document.tables[0].cells).toHaveLength(9); });
  it("applies the page homography",()=>expect(transformPoint([10,20],[2,0,5,0,2,7,0,0,1])).toEqual([25,47]));
});
