import { useEffect, useMemo, useRef, useState } from "react";
import DiagnosticsPanel from "./components/DiagnosticsPanel";
import Worksheet from "./components/Worksheet";
import { exportCanonicalWorkbook } from "./lib/exportWorkbook";
import { buildCanonicalDocument } from "./lib/fusion";
import { geometryWorker } from "./lib/geometryWorker";
import { prepareImageForOcr, type PreparedImage } from "./lib/imagePreparation";
import { flattenOcr, recognizeImage } from "./lib/ocrClient";
import type { BrowserGeometryResult, CanonicalDocument } from "./types/canonical";

const emptyGeometry = (width: number, height: number, reason: string): BrowserGeometryResult => ({ page_transform: { sourceWidth: width, sourceHeight: height, targetWidth: width, targetHeight: height, forward: [1,0,0,0,1,0,0,0,1], inverse: [1,0,0,0,1,0,0,0,1], perspectiveApplied: false, deskewDegrees: 0 }, table_candidates: [], horizontal_lines: [], vertical_lines: [], row_boundaries: [], column_boundaries: [], cell_rectangles: [], diagnostics: { geometryFallback: reason } });
const formatBytes = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(2)} MB`;
type ViewTab = "worksheet" | "diagnostics";

export default function App() {
  const [file, setFile] = useState<File | null>(null); const [prepared, setPrepared] = useState<PreparedImage | null>(null); const [canonical, setCanonical] = useState<CanonicalDocument | null>(null); const [stage, setStage] = useState("Choose an invoice image"); const [progress, setProgress] = useState(0); const [processing, setProcessing] = useState(false); const [exporting, setExporting] = useState(false); const [error, setError] = useState<string | null>(null); const [tab, setTab] = useState<ViewTab>("worksheet"); const abortRef = useRef<AbortController | null>(null);
  useEffect(() => () => { abortRef.current?.abort(); geometryWorker.cancel(); }, []);
  useEffect(() => () => { if (prepared?.previewUrl) URL.revokeObjectURL(prepared.previewUrl); }, [prepared?.previewUrl]);
  const summary = useMemo(() => canonical ? { tables: canonical.tables.length, cells: canonical.tables.reduce((sum, table) => sum + table.cells.length, 0), unresolved: canonical.unassignedOcr.length } : null, [canonical]);
  const selectFile = (next: File | null) => { if (prepared?.previewUrl) URL.revokeObjectURL(prepared.previewUrl); setPrepared(null); setCanonical(null); setError(null); setFile(next); setStage(next ? "Ready to process" : "Choose an invoice image"); setProgress(0); };
  const cancel = () => { abortRef.current?.abort(); geometryWorker.cancel(); setProcessing(false); setStage("Cancelled"); };
  const processImage = async () => {
    if (!file || processing) return; const controller = new AbortController(); abortRef.current = controller; setProcessing(true); setCanonical(null); setError(null); setProgress(4); let next: PreparedImage | null = null;
    try {
      setStage("Correcting orientation and preparing upload"); next = await prepareImageForOcr(file); setPrepared((old) => { if (old?.previewUrl) URL.revokeObjectURL(old.previewUrl); return next; }); setProgress(18);
      const bitmap = await createImageBitmap(next.uploadBlob); setStage("Detecting page and table geometry in browser");
      const geometryPromise = geometryWorker.analyze(bitmap, ({ stage: s, progress: p }) => { setStage(s); setProgress(Math.max(18, Math.min(62, 18 + p * 0.44))); }, controller.signal).catch((geometryError: unknown) => { if (controller.signal.aborted) throw geometryError; return emptyGeometry(next!.processedWidth, next!.processedHeight, String(geometryError)); });
      setStage("Reading text with standalone RapidOCR"); const ocrPromise = recognizeImage(next.uploadBlob, file.name, controller.signal); const [geometry, ocr] = await Promise.all([geometryPromise, ocrPromise]); setProgress(82); setStage("Assigning OCR boxes to explicit cells");
      const document = buildCanonicalDocument({ fileName: file.name, originalBytes: next.originalBytes, processedBytes: next.processedBytes, originalWidth: next.originalWidth, originalHeight: next.originalHeight, processedWidth: next.processedWidth, processedHeight: next.processedHeight, mimeType: next.mimeType, geometry, ocr: flattenOcr(ocr), ocrDiagnostics: { processingTimeMs: ocr.processingTimeMs, ocrProcessingTimeMs: ocr.ocrProcessingTimeMs, modelInformation: ocr.modelInformation, errors: ocr.errors } });
      setCanonical(document); setTab("worksheet"); setProgress(100); setStage("Editable worksheet ready");
    } catch (caught) { geometryWorker.cancel(); if ((caught as DOMException)?.name !== "AbortError") { setError(caught instanceof Error ? caught.message : String(caught)); setStage("Processing failed"); } } finally { setProcessing(false); abortRef.current = null; }
  };
  const changeCell = (tableId: string, cellId: string, text: string) => setCanonical((current) => current ? { ...current, tables: current.tables.map((table) => table.id !== tableId ? table : { ...table, cells: table.cells.map((cell) => cell.id === cellId ? { ...cell, text, manuallyEdited: true, warning: null } : cell) }) } : current);
  const exportWorkbook = async () => { if (!canonical || exporting) return; setExporting(true); setError(null); try { await exportCanonicalWorkbook(canonical); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } finally { setExporting(false); } };
  return <main className="app-shell"><header className="hero"><div><span className="eyebrow">Browser-first cell reconstruction</span><h1>Image to editable Excel</h1><p>RapidOCR reads text. OpenCV.js reconstructs geometry. Blank cells stay blank instead of shifting values left.</p></div><div className="architecture-badge">No database · XLSX generated locally</div></header><section className="upload-card"><label className="drop-zone"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => selectFile(event.target.files?.[0] ?? null)} /><strong>{file ? file.name : "Choose PNG, JPEG or WebP"}</strong><span>{file ? formatBytes(file.size) : "Orientation is corrected before a bounded OCR upload."}</span></label><div className="actions"><button className="primary" disabled={!file || processing} onClick={processImage}>{processing ? "Processing…" : "Reconstruct worksheet"}</button>{processing && <button className="secondary" onClick={cancel}>Cancel</button>}{canonical && <button className="secondary" disabled={exporting} onClick={exportWorkbook}>{exporting ? "Building XLSX…" : "Download XLSX"}</button>}</div><div className="progress-row"><div><span style={{ width: `${progress}%` }} /></div><p>{stage}</p></div>{error && <p className="error-banner">{error}</p>}{prepared && <div className="prepared-summary"><img src={prepared.previewUrl} alt="Processed invoice preview" /><div><strong>{prepared.processedWidth} × {prepared.processedHeight}</strong><span>{formatBytes(prepared.processedBytes)} upload · {prepared.mimeType}</span>{prepared.warnings.map((warning) => <p key={warning}>{warning}</p>)}</div></div>}</section>{canonical && <section className="results-section"><div className="result-toolbar"><div className="stats"><span><strong>{summary?.tables}</strong> tables</span><span><strong>{summary?.cells}</strong> cells</span><span><strong>{summary?.unresolved}</strong> unresolved</span></div><div className="tabs"><button className={tab === "worksheet" ? "active" : ""} onClick={() => setTab("worksheet")}>Worksheet</button><button className={tab === "diagnostics" ? "active" : ""} onClick={() => setTab("diagnostics")}>Diagnostics</button></div></div>{tab === "worksheet" ? <Worksheet document={canonical} onCellChange={changeCell} /> : <DiagnosticsPanel document={canonical} />}</section>}</main>;
}
